"""initial schema

Revision ID: 4ea37a2d48bd
Revises: 
Create Date: 2026-05-19 15:09:34.133858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ea37a2d48bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('last_profit_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission_asset', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_order_status'), ['order_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_symbol'), ['symbol'], unique=False)

    op.create_table('pricealert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricealert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricealert_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricealert_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricealert_user_id'), ['user_id'], unique=False)

    op.create_table('tradingaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('use_bnb_fee', sa.Boolean(), nullable=False),
    sa.Column('trading_volume_30d', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fee_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userachievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userachievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userachievement_achievement_key'), ['achievement_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_userachievement_user_id'), ['user_id'], unique=False)

    op.create_table('usermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mission_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usermission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usermission_user_id'), ['user_id'], unique=False)

    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tradingaccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactionhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee_asset', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_maker', sa.Boolean(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactionhistory')
    op.drop_table('position')
    with op.batch_alter_table('usermission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usermission_user_id'))

    op.drop_table('usermission')
    with op.batch_alter_table('userachievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userachievement_user_id'))
        batch_op.drop_index(batch_op.f('ix_userachievement_achievement_key'))

    op.drop_table('userachievement')
    op.drop_table('tradingaccount')
    with op.batch_alter_table('pricealert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricealert_user_id'))
        batch_op.drop_index(batch_op.f('ix_pricealert_symbol'))
        batch_op.drop_index(batch_op.f('ix_pricealert_is_active'))

    op.drop_table('pricealert')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_symbol'))
        batch_op.drop_index(batch_op.f('ix_order_order_status'))

    op.drop_table('order')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
