"""add refresh tokens

Revision ID: adea1cb3fc9a
Revises: 4ea37a2d48bd
Create Date: 2026-05-19 15:59:40.965123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adea1cb3fc9a'
down_revision: Union[str, Sequence[str], None] = '4ea37a2d48bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('rotated_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refreshtoken_revoked'), ['revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_refreshtoken_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refreshtoken_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refreshtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refreshtoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_refreshtoken_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refreshtoken_revoked'))

    op.drop_table('refreshtoken')
    # ### end Alembic commands ###
