"""engagement features

Revision ID: ae90200a58cf
Revises: adea1cb3fc9a
Create Date: 2026-05-19 17:25:18.465165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae90200a58cf'
down_revision: Union[str, Sequence[str], None] = 'adea1cb3fc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_is_active'), ['is_active'], unique=False)

    op.create_table('activityfeed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activityfeed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activityfeed_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activityfeed_user_id'), ['user_id'], unique=False)

    op.create_table('dailycheckin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('streak_day', sa.Integer(), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dailycheckin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dailycheckin_checkin_date'), ['checkin_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dailycheckin_user_id'), ['user_id'], unique=False)

    op.create_table('seasonranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('return_pct', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasonranking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasonranking_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seasonranking_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkin_streak', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_checkin_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('referred_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referral_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_user_referral_code'), ['referral_code'], unique=True)
        batch_op.create_foreign_key('fk_user_referred_by', 'user', ['referred_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_referred_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_referral_code'))
        batch_op.drop_column('referral_count')
        batch_op.drop_column('referred_by_user_id')
        batch_op.drop_column('referral_code')
        batch_op.drop_column('last_checkin_date')
        batch_op.drop_column('checkin_streak')

    with op.batch_alter_table('seasonranking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasonranking_user_id'))
        batch_op.drop_index(batch_op.f('ix_seasonranking_season_id'))

    op.drop_table('seasonranking')
    with op.batch_alter_table('dailycheckin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dailycheckin_user_id'))
        batch_op.drop_index(batch_op.f('ix_dailycheckin_checkin_date'))

    op.drop_table('dailycheckin')
    with op.batch_alter_table('activityfeed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activityfeed_user_id'))
        batch_op.drop_index(batch_op.f('ix_activityfeed_created_at'))

    op.drop_table('activityfeed')
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_is_active'))

    op.drop_table('season')
    # ### end Alembic commands ###
