"""futures and bankruptcy

Revision ID: f87e2fd30c7a
Revises: ae90200a58cf
Create Date: 2026-05-19 20:02:15.647809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f87e2fd30c7a'
down_revision: Union[str, Sequence[str], None] = 'ae90200a58cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futuresposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('margin', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('liquidation_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_liquidated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('futuresposition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_futuresposition_is_open'), ['is_open'], unique=False)
        batch_op.create_index(batch_op.f('ix_futuresposition_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_futuresposition_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bankruptcy_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_bankruptcy_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_bankruptcy_date')
        batch_op.drop_column('bankruptcy_count')

    with op.batch_alter_table('futuresposition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_futuresposition_user_id'))
        batch_op.drop_index(batch_op.f('ix_futuresposition_symbol'))
        batch_op.drop_index(batch_op.f('ix_futuresposition_is_open'))

    op.drop_table('futuresposition')
    # ### end Alembic commands ###
